logging:
  level:
    root: error

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:crud
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
